### ISSUE TITLE
Samsung Internet v26.0.3.7 unstable fingerprint changing

### ISSUE THREAD

**Issue by egoryan8** [fingerprintjs/fingerprintjs#1030]
With each new request, the fingerprint in the Samsung Internet v26.0.3.7 browser changes 

fingerprintjs version is 4.5.0

**Comment by fitz0z** [comment]
+

**Comment by Valve** [comment]
@egoryan8 please identify which component is changing with each request and exclude this component using this [guide](https://github.com/fingerprintjs/fingerprintjs/blob/master/docs/extending.md).

**Comment by Finesse** [comment]
@Valve, looks like this is an issue that should be fixed on our side, because it happens in a popular browser, happens always and produces a different fingerprint each time. So I've reopened the issue.

Like canvas anti-fingerprinting implemented in Samsung Internet earlier (https://github.com/fingerprintjs/fingerprintjs/issues/791), this behavior is purposeful. It can be disabled in the browser setting: "Privacy dashboard" → "Smart anti-tracking".

I've added this problem to my backlog and will try to solve it later.
