### ISSUE TITLE
WebRTC connection breaks browser back/forward cache

### ISSUE THREAD

**Issue by pondchamp** [fingerprintjs/fingerprintjs#1052]
### Scenario

I am running the `@fingerprintjs/fingerprintjs-pro-react` in my NextJS 14 app, and while I was working with [Lighthouse CI](https://github.com/GoogleChrome/lighthouse-ci) to optimise my site, I noticed that my site was failing the `bf-cache: Page prevented back/forward cache restoration` assertion. To reproduce this issue, I used Chrome DevTools (Application > Background services > Back/forward cache) to identify that the fingerprint loader file is being served through WebRTC, which results in the Chrome browser disabling the back/forward cache.

The [web.dev docs](https://web.dev/articles/bfcache?utm_source=devtools#close-open-connections) indicate that WebRTC connections need to be closed explicitly on `pagehide` or `freeze` events and reopened on `pageshow` or `resume` events - would this be something that could be added in as event listeners within the `FpjsProvider` context component?

### Browser
Chromium Edge, Win11

### FPJS NPM Versions
"@fingerprintjs/fingerprintjs-pro": "^3.8.2"
"@fingerprintjs/fingerprintjs-pro-react": "^2.3.1"

**Comment by Finesse** [comment]
Hi @pondchamp. Thank you for letting us know and providing an information to help solving the problem. This is a known problem, and we plan to solve it soon.

I'm closing the issue because it regards Fingerprint Pro, but this is the FingerprintJS repository (they are related but different tools). Feel free to leave a comment if you have further questions or suggestions.
