### ISSUE TITLE
[Feature suggestion] See changing canvas fingerprint as a boolean value

### ISSUE THREAD

**Issue by ghost** [fingerprintjs/fingerprintjs#411]
Hi,

I was thinking that another vector fingerprintjs2 could use is "Changes canvas fingerprint on each request". This would be a boolean value. It would allow for better fingerprinting of browsers which change their fingerprint on each request. The combination of this boolean and other values can result in a unique fingerprint.

**Comment by nebi-frame** [comment]
is it possible a same browser to change its canvas while making sequential request?

**Comment by Finesse** [comment]
In order to check that separate page views of the same visitor produce different canvas fingerprints, the fingerprint needs to be linked to together. Linking requires storing information in browser. Storing information is opposite to what this library is designed for (identify without leaving a trace).

If you need high accuracy even for browsers that change canvas fingerprints, please consider the [pro version](https://fingerprintjs.com) ([how to migrate in 30 seconds](https://dev.fingerprintjs.com/v3/docs/migrating-from-previous-versions#from-fingerprintjs-open-source-version-3)).

> is it possible a same browser to change its canvas while making sequential request?

Tor does it.
