### ISSUE TITLE
When Fingerprint Components are empty?

### ISSUE THREAD

**Issue by VladSavitsky** [fingerprintjs/fingerprintjs#542]
### Scenario

In some cases (more then 100) I've got empty components array.
JS works and supported. What could cause this?
How could I debug this cases?

Thanks.

**Comment by Finesse** [comment]
@VladSavitsky Sorry for the long reply.

In order to debug, please provide your code that uses FingerprintJS. Also watch the browser console for errors and other messages related to FingerprintJS; if you have many users, you can collect console logs automatically with a service like [Rollbar](https://rollbar.com/), [Bugsnag](https://www.bugsnag.com) or [Sentry](https://sentry.io/) (make sure your code sends a report when it gets an empty components array).

**Comment by Finesse** [comment]
Closing this due to the lack of response. Feel free to add a reply.
