### ISSUE TITLE
Publish the library as @fingerprintjs/fingerprintjs on NPM

### ISSUE THREAD

**Issue by Valve** [fingerprintjs/fingerprintjs#549]
Update CDNs accordingly as well.

**Comment by Finesse** [comment]
@Valve I suggest to discard cdnjs.com and use an automatic CDN instead, for example unpkg.com. I don't link cdnjs.com because it requires manual actions and human review for publishing. Just compare: [package configuration manual on cdnjs](https://github.com/cdnjs/packages/blob/master/CONTRIBUTING.md#configuring-library-auto-update) and zero maintenance burden on other CDNs. And Cloudflare CDN (cndjs.com) isn't the fastest according to https://www.cdnperf.com.

**Comment by Valve** [comment]
Let's discuss if we should go with something like unpkg or use CloudFront.

**Comment by Finesse** [comment]
Done: https://www.npmjs.com/package/@fingerprintjs/fingerprintjs. v2.1.3 will be published within a day.

The new CDN URLs:

- [//cdn.jsdelivr.net/npm/@fingerprintjs/fingerprintjs@2/dist/fingerprint2.min.js](https://cdn.jsdelivr.net/npm/@fingerprintjs/fingerprintjs@2/dist/fingerprint2.min.js)
- [//unpkg.com/@fingerprintjs/fingerprintjs@2/dist/fingerprint2.min.js](https://unpkg.com/@fingerprintjs/fingerprintjs@2/dist/fingerprint2.min.js)
