### ISSUE TITLE
0.5.x releases disappeared from repository

### ISSUE THREAD

**Issue by AngeloAvv** [fingerprintjs/fingerprintjs#550]
As reported in the title, it seems that the releases above 0.5.1 disappeared from Github. 
Did you delete them? Actually it's a bad practice to delete older releases.

This has broken our projects (more than 50) which use your legacy (0.5.3 and 0.5.4) releases.
We were running a release cycle which takes several weeks and now we have to start from the beginning

**Comment by Finesse** [comment]
@AngeloAvv We've made a couple of repository renames recently and this is probably not the repository you're looking for. Sorry for the inconvenience. Anyway GitHub isn't a good source of code in automated pipelines. You can get 0.5.2 and 0.5.3 from https://www.npmjs.com/package/fingerprintjs ("Versions" tab). You'd rather rely on NPM than GitHub because NPM keeps old versions and packages regardless. Please let me know if it solves your issue.

@Valve Looks like Angelo relies on the legacy http://github.com/Valve/fingerprint repository that redirects here now. I haven't found it in your profile. Can Angelo get it somewhere?

**Comment by AngeloAvv** [comment]
@Finesse by looking into one of our yarn.lock files, we have the following reference:

```
fingerprint@Valve/fingerprintjs#~0.5.4:
  version "0.5.3"
  resolved "https://codeload.github.com/Valve/fingerprintjs/tar.gz/e723d1befe1aae50a995127399e6738ed6600e72"
```

If we are forced to change the references, we can go with the release 0.6.0, but we first need to make sure it won't break our projects (we work in a particular field where QA requires longer times)

**Comment by Finesse** [comment]
@AngeloAvv Just reinstall the package: `yarn remove fingerprintjs && yarn add fingerprintjs`. Version 0.5.3 (that is used according to your code) will be downloaded from NPM and your code will work.

**Comment by AngeloAvv** [comment]
@Finesse strange behavior. We were referencing 0.5.3 in the yarn lock, but after comparing the old projects with the updated ones as you suggested, we saw these two things.

* The old Valve fingerprint.js file has the main comment section which says to be the 0.5.5 release:
`* fingerprintJS 0.5.5 - Fast browser fingerprint library`

* There are some differences in the code between them:
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/7781143/93187421-14f83580-f740-11ea-9eed-4be796401c4a.png)

What should we do? Would it be better to go with 0.6.0?

**Comment by Finesse** [comment]
@AngeloAvv There are 2 fingerprintjs libraries. The first is the one you use. It's available at https://www.npmjs.com/package/fingerprintjs. Its last version was released 7 years ago and no it isn't maintained anymore. Its GitHub repository isn't here, it was at http://github.com/Valve/fingerprintjs, now it's gone. @Valve, can we release the missing legacy versions to NPM so that guys like Angelo can use it?

The second is the current repository. It's under development and available at https://www.npmjs.com/package/@fingerprintjs/fingerprintjs and https://github.com/fingerprintjs/fingerprintjs. It never had v0.5.2–5. The v0.5.* here aren't the same packages as v0.5.* in the legacy repository.

**Comment by Valve** [comment]
@AngeloAvv unfortunately this old/legacy repository is no longer supported, it has been archived for several years. 
We removed it yesterday and set up a redirect to this repo.

You can keep using existing NPM packages, but we will not be pushing new packages for that legacy package. 
I apologize for the inconvenience.

**Comment by Finesse** [comment]
@AngeloAvv There are forked of the repository you need on GitHub: https://libraries.io/github/Valve/fingerprintjs/forks. Find the version you need, fork it to your GitHub account and install it from your fork.

**Comment by Valve** [comment]
@bradacina I'm sorry that it happened with your build. 
Unfortunately, we no longer support this version and removed it.

**Comment by bradacina** [comment]
Meh, I doubt anyone expected any "support" for a 6 year old version of the library. It would have been nice to have it cached somewhere to keep the legacy system builds happy.

**Comment by Valve** [comment]
@bradacina we do have it cached on our NPM account: https://www.npmjs.com/package/fingerprintjs
It wasn't removed from NPM registry, we just removed the github project.

**Comment by riverbankeu** [comment]
Thank you. It doesn't have the 0.5.4 version but at least there's 0.5.3.

**Comment by Finesse** [comment]
> Thank you. It doesn't have the 0.5.4 version but at least there's 0.5.3.

@riverbankeu Version 0.5.3 of `fingerprintjs2` (the one stored in this repository) is not the same version as 0.5.3 of `fingerprintjs` (the one that you are probably looking for). If you need 0.5.4 of `fingerprintjs`, then see https://github.com/fingerprintjs/fingerprintjs/issues/550#issuecomment-692708691.

**Comment by riverbankeu** [comment]
Thank you for that @Finesse. We made our own fork from what looks to be the most recent fork from that page.
