### ISSUE TITLE
Available screen resolution changes when in fullscreen mode on MacOS

### ISSUE THREAD

**Issue by Valve** [fingerprintjs/fingerprintjs#568]
When I'm entering full screen mode in MacOS Chrome the fingerprint changes because of the available screen resolution.

**Comment by Finesse** [comment]
@Valve Have you heard about similar behavior on other OSs?

**Comment by Valve** [comment]
It can happen on any OS, but it's more common on MacOS (because it's easy to enter a full-screen mode there).
On windows you would need to type F11 to enter a full-screen mode and for this reason not as common.

**Comment by Finesse** [comment]
I've found out that old versions of Firefox for Android change screen resolution depending on the device orientation. I'll post a full research result later.

**Comment by Finesse** [comment]
- Chrome on macOS:
    - Versions 42, 50, 55, 56, 70, 79, 80, 81, 84, 87 do change the available screen resolution depending on the dock size and fullscreen on/off.
    - Versions 57, 58, 61, 70, 78 don't change available screen resolution after turning fullscreen on/off.
- Chrome, Firefox, Edge 18 and IE 11 on Windows. The dock size and position is detected, but I don't know if there is a fullscreen mode like in macOS on Windows, so I can't say whether "fullscreen" affects the result. Dock hiding isn't a fullscreen that I mean because it's a setting.
- Firefox on macOS: versions 48, 56, 65, 73, 82 do change the available screen resolution depending on the dock size and fullscreen on/off.
- Safari and Chrome on iPhone and iPad (including split view): iOS 9 subtracts the height of the top bar from the available screen height in the portrait orientation. iOS 10, 11, 12, 13, 14 always return the screen resolution as the available screen resolution. The screen size is always the actual screen size in CSS units.
- Chrome on Android: versions 42 on Android 6, 83 on Android 9, 83 on Android 10 (including split view on Galaxy Tab S7), 86 on Android 6 behave the same as iOS 10.
- Firefox on Android:
    - Versions 49, 61, 68 on Android 6 change both screen resolution and available screen resolution depending on the device orientation (subtract the top bar height from the height).
    - Versions 79, 82 on Android 7, 80 on Android 10 behave the same as iOS 10.
- Android browser: version 6 (more to be examined) behaves the same as iOS 10.

Also I've checked how calling [requestFullscreen](https://developer.mozilla.org/en-US/docs/Web/API/Element/requestFullscreen) affects the values:

- Chrome on Windows:
    - Versions 42, 78, 79, 83 don't change the available screen resolution.
    - Versions 84, 84, 86 do change the available screen resolution.
- Firefox on Windows: versions 48, 56, 65, 73, 82 don't change the available screen resolution.
- Firefox on macOS: versions 48, 56, 65, 73, 82 do change the available screen resolution.
- Edge 18 and IE 11 on Windows don't change the available screen resolution.

My thoughts:

- The fact that resizing dock changes fingerprint should be an expected behavior. I think visitors change dock size very seldom, and the dock size is a good source of entropy.
- We can neglect the `requestFullscreen` cases and ask library users to not get a fingerprint when a `requestFullscreen` effect is active.

**Comment by Finesse** [comment]
I've found a fullscreen mode in Windows: press F11. Toggling this fullscreen mode doesn't change the available screen resolution (in contrast to the programmatic fullscreen mode).

**Comment by Finesse** [comment]
The conversation has moved to https://github.com/fingerprintjs/fingerprintjs/pull/585
