### ISSUE TITLE
Problem to import @fingerprintjs/fingerprintjs

### ISSUE THREAD

**Issue by IrvingSG** [fingerprintjs/fingerprintjs#586]
> help wanted

Hello. I'm new with npm modules, I'm trying to use fingerprintjs in a Symfony Project (v3.4).
I already run this command: 
`npm i @fingerprintjs/fingerprintjs `
And it already appears in package.json file correctly.
This is the way I'm trying to use this module, in my html.twig file, I have the following script to test:
```
  <script type="module">
        import FingerprintJS from '@fingerprintjs/fingerprintjs';
        function initFingerPrint(){
            (async () => {
                // We recommend to call `load` at application startup.
                const fp = await FingerprintJS.load();

                // The FingerprintJS agent is ready.
                // Get a visitor identifier when you'd like to.
                const result = await fp.get();

                // This is the visitor identifier:
                const visitorId = result.visitorId;
                console.log(visitorId);
            })();
        }
    </script>
```
But when I open my project in the Browser, I got this error:
`Failed to resolve module specifier "@fingerprintjs/fingerprintjs". relative references must start with either / ./ or ../`
I've searched some information about how to fix this problem or how to import fingerprintjs in the correct way but I did not get success.
I'm new working with npm and fingerprintjs, I hope someone can help me with this topic.
Regards.

**Comment by Valve** [comment]
Hi @IrvingSG , thanks a lot for using our open-source library!
We'll get back to you with a detailed reply shortly.

**Comment by Finesse** [comment]
@IrvingSG You mix 2 distinct ways of embedding JavaScript into a website. Mixing isn't allowed.

The first is native browser way. It requires no additional tools, you just type a code that works immediately. It can be used by typing `<script> ... </script>` in an HTML code. When you use `import`, browser tries to search the file you mention after `import ... from` using the following rules:

- If the path starts with `./`, then browser appends the path to the current page URL
- If the path starts with `../`, then browser appends the path to the parent path of the current page URL
- If the path starts with `/`, then browser appends the path to the current page domain
- Otherwise browser emits an error

In most cases there is even no way for browser to access content of `node_modules` directory (the directory where NPM installs packages).

The second is to use [Node.js](https://nodejs.org/) syntax and convert it the native syntax using a bundler like [Webpack](https://webpack.js.org) or [Rollup](https://rollupjs.org/). This approach allows to use the short Node.js import syntax that you've shown in your example, because bundlers know exact files that stands behind short declarations.

Another your mistake is that you declare the `initFingerPrint` function, but never call it, therefore it never runs.

-----------

I suppose you are not an experienced JavaScript developer. If so, then you should use the native way. You need to specify a full path to the JS file you want to import. You can put the FingerprintJS JS file to different locations:

1. Take it from a CDN. The file is already uploaded to a web server, you don't need to use NPM. Just put the following code into your HTML:
    ```html
    <script>
      function initFingerprintJS() {
        FingerprintJS.load().then(fp => {
          // The FingerprintJS agent is ready.
          // Get a visitor identifier when you'd like to.
          fp.get().then(result => {
            // This is the visitor identifier:
            const visitorId = result.visitorId;
            console.log(visitorId);
          });
        });
      }
    </script>
    <script
      async
      src="//cdn.jsdelivr.net/npm/@fingerprintjs/fingerprintjs@3/dist/fp.min.js"
      onload="initFingerprintJS()"
    ></script>
    ```
2. Upload it to you server and take from your server. First you must run `npm i @fingerprintjs/fingerprintjs` from inside the `public` directory or create a symbolic link to the `node_modules` directory in the `public` directory, otherwise browser don't have access to the file. Then use the following HTML code:
    ```html
    <script>
      function initFingerprintJS() {
        FingerprintJS.load().then(fp => {
          // The FingerprintJS agent is ready.
          // Get a visitor identifier when you'd like to.
          fp.get().then(result => {
            // This is the visitor identifier:
            const visitorId = result.visitorId;
            console.log(visitorId);
          });
        });
      }
    </script>
    <script
      async
      src="/node_modules/@fingerprintjs/fingerprintjs/dist/fp.min.js"
      onload="initFingerprintJS()"
    ></script>
    ```
    The library doesn't support using `import ... from ...` in native browser environment (there is [a separate issue](https://github.com/fingerprintjs/fingerprintjs/issues/573) for this), so you won't be able to use `import` unless you use the Node.js way.

Feel free to ask additional questions if you need more help.

**Comment by IrvingSG** [comment]
Thanks a lot! Yes I'm very new with Javascript and using npm Packages, I´ve tried the examples that you gave me,and I prefered to use the 2nd Option(Uploaded to my server), I run the `npm i @fingerprintjs/fingerprintjs` ,but I noticed that the `fp.min.js` file was not added into the node_modules directory.
![image](https://user-images.githubusercontent.com/52004812/100135571-7418ab80-2e4f-11eb-8c5a-8187832a5b2d.png)

FYI! I'm trying to use npm because of the pc's where I pretend to open my website does not have Internet Access, so I decided import it into my local server.

Thank you so much.

**Comment by neilabdev** [comment]
Forgive me, not a JS master here... but, using a stimulus controller (from Rails) I receive the following browser error:


> Error: Unable to resolve specifier '@fingerprintjs/fingerprintjs' imported from http://localhost:300/path/..

The valued note   [above](https://github.com/fingerprintjs/fingerprintjs/issues/586#issuecomment-732662765) by [Finesse](https://github.com/Finesse) suggest this should work, but have to specify the url as in the example below to get it to work. 


> The second way is to use [Node.js](https://nodejs.org/) syntax and convert it the native syntax using a bundler like [Webpack](https://webpack.js.org/) or [Rollup](https://rollupjs.org/). Node.js syntax allows to use package names as import paths, therefore the bundlers transform such paths into concrete JS file paths.



```js
import { Controller } from "@hotwired/stimulus"
import FingerprintJS from  'https://openfpcdn.io/fingerprintjs/v3'
//import * as FingerprintJS from '@fingerprintjs/fingerprintjs' // FIXME: this should work

export default class extends Controller {
    static targets = ['acceptance']

    connect() {
        console.log(`your signature: ${this.visitorIdentifier}`)
    }

    get visitorIdentifier() {
        // Initialize an agent at application startup.
        const fpPromise = FingerprintJS.load(); 

        // Get the visitor identifier when you need it.
        fpPromise
            .then(fp => fp.get())
            .then(result => console.log(result.visitorId))
    }
}
```


I'm stumped, but using the url for now... hopefully this mystery is useful to others. Thx :)

**Comment by Finesse** [comment]
@neilabdev Your URL solutions is correct. You can also use dynamic import:

```js
const FingerprintJS = await import('https://openfpcdn.io/fingerprintjs/v3')
```

But your problem is not specific to FingerprintJS. Please seek for help in Rails community. You need to learn how to use Node.js packages with the framework.
