### ISSUE TITLE
Fingerprint 3 doesn't allows us to input the options we need for generating fingerprint

### ISSUE THREAD

**Issue by jyyang42** [fingerprintjs/fingerprintjs#590]
Fingerprint 2 can let us choose what options we need for generating fingerprint. Can version 3 support that as well? Basically expose an API for users to choose the sources in `getBuiltinComponents`

**Comment by Finesse** [comment]
This topic is described in [the customization section in the v2-v3 migration guide](https://github.com/fingerprintjs/fingerprintjs/blob/master/docs/migrating_v2_v3.md#customization). There must be a good reason to introduce a complexity, so If you need extra options that change `load()` or `get()` behavior, please explain why you need them.

**Comment by jyyang42** [comment]
Hi @Finesse, thanks for you reply. We are trying to integrate Fingerprint package to our system, then we found there's a high latency that's introduces. Depends on users' computer, the p99 latency is around 100ms ~ 20s, and the user wait time will be non-acceptable. Thus wanted to know if it is possible to exclude some of the high latency calls from the get method.

**Comment by Finesse** [comment]
> Depends on users' computer, the p99 latency is around 100ms ~ 20s

@jyyang42 Do you really mean 20 seconds? Please provide debug data for a long running identification, it'll show the exact entropy sources that take long to run.

**Comment by jyyang42** [comment]
@Finesse, so I've been collecting data for these days, for timing mean, the grey spikes are from audio, blue spikes are from fonts, and some other smaller spikes are from canvas. (millisecond)
![image](https://user-images.githubusercontent.com/32890784/101449330-6fd3a000-38dd-11eb-97ad-a4a5b3794841.png)
Taking a closer look at the none spiky peace time (also from timing mean): 
![image](https://user-images.githubusercontent.com/32890784/101450128-dd340080-38de-11eb-8b53-5f9df9fdf699.png)

When we look at upper99 it sometimes went crazy. the spikes are mostly from audio, and canvas, sometimes font.
![image](https://user-images.githubusercontent.com/32890784/101450335-44ea4b80-38df-11eb-9cc4-d3dc05d48a43.png)

So wondering if I can exclude audio and canvas, maybe also font from the fingerprint calculation 🤔

**Comment by Finesse** [comment]
@jyyang42 Thank you for the afford. It's hard to perceive charts when you don't know the axes scales and meanings; Y-axis is number of identifications I guess and X is I don't know what.

Audio component can take much time when identification runs in background (i.e. another browser tab is active now). Some browsers (we know about cases in Safari on iPhone) don't let run audio component in background, therefore agent waits while the page goes foreground when it can't get audio fingerprint immediately. We consider it as a normal behavior because users don't expect fast reaction when page is in background.

Could you please explain why you need fingerprinting to run very fast. If you need a fast UI reaction, you can get a fingerprint when the page starts and use it immediately when it's required; is it an option for you?
