### ISSUE TITLE
What are the chances of same fingerprint generated for in app browser?

### ISSUE THREAD

**Issue by neelkanthdaffodil** [fingerprintjs/fingerprintjs#612]
Is it possible that same fingerprint gets generated for the in-app browser (not the mobile browser)

**Comment by Finesse** [comment]
It can be possible on iOS (because every browser and WebView use the same engine) and in Chrome on Android (for the same reason). We haven’t checked it. I will appreciate a lot if you check and let me know the result.

**Comment by llaakso** [comment]
Same fingerprints are very common, notably on iPhones. One should consider fingerprint as a _possibility_ of same user.

**Comment by neelkanthdaffodil** [comment]
@Finesse @llaakso Actually What best can be done to reduce the probability of same fingerprints?

**Comment by Finesse** [comment]
> Same fingerprints are very common, notably on iPhones. One should consider fingerprint as a _possibility_ of same user.

Sure. Fingerprinting is an identification technique with its pros and cons, it's not an ultimate solution. You can combine multiple techniques to achieve better accuracy.

> Actually What best can be done to reduce the probability of same fingerprints?

There is nothing you can do to improve _fingerprint_ accuracy at the moment. But you can improve _identification_ accuracy by combining fingerprint with a cookie and the public IP address. For example, if 2 iPhones have no cookie, have the same fingerprint and different IP addresses, then treat them as different devices and put different cookies onto them; next time they will return with the cookies, you'll know that they are separate devices because they have different cookies. Actually, this is not a trivial topic; probably, we will make an article on this.

Also you can try FingerprintJS Pro that combines fingerprinting with a couple extra identification techniques and uses a tricky algorithm to make decisions based on the data ([30 seconds migration guide](https://dev.fingerprintjs.com/docs/migrating-from-previous-versions#from-fingerprintjs-open-source-version-3)).

**Comment by neelkanthdaffodil** [comment]
@Finesse I just stumbled upon this this update by Firefox [](https://blog.mozilla.org/security/2020/01/07/firefox-72-fingerprinting/)

It says that Firefox 72 will block third-party fingerprinting resources. I am just curious to know what effect this will have on the fingerprintjs.

**Comment by Finesse** [comment]
@neelkanthdaffodil It doesn't block at the moment. It won't be able to block FingerprintJS if you install it via NPM and bundle with your code using a tool like Webpack or Rollbar.

**Comment by Finesse** [comment]
Closing because of the discussion has stopped

**Comment by Valve** [comment]
@neelkanthdaffodil are you still interested in this feature? We're collecting feedback from our library users about the implementation. Would you be interested to get on a quick call to discuss it?

**Comment by melvinchng** [comment]
@Valve I am interested in this feature.

**Comment by Valve** [comment]
@melvinchng can we get on a 15-min call to discuss it? 
https://calendly.com/fpjs-valentin/15min

**Comment by Mkadir** [comment]
> It can be possible on iOS (because every browser and WebView use the same engine) and in Chrome on Android (for the same reason). We haven’t checked it. I will appreciate a lot if you check and let me know the result.

Hi @Finesse ! 
Webapp can be used through Telegram bots. A WebView opens inside Telegram and the integration is up to you. In this case, one device and the WebView engine are the same chrome, but the telegram clients are different. For example iMe and Plus messenger. This is returning two different ids for the two clients. But one device. How can we fix that?

**Comment by JuroUhlar** [comment]
This piece of documentation might be relevant to your problem: https://dev.fingerprint.com/docs/identifying-in-app-browsers-for-ios

**Comment by Mkadir** [comment]
@JuroUhlar thanks for reply, but my problem was in android. Telegram have web applications you know, and i use fingerprintjs for it to identify device, but something was wrong with telegram i dont know how to fix. 

```
<script>
  const fpPromise = import('https://openfpcdn.io/fingerprintjs/v4')
    .then(FingerprintJS => FingerprintJS.load())
  fpPromise
    .then(fp => fp.get())
    .then(result => {
      const visitorId = result.visitorId
      console.log(visitorId)
    })
</script>
```

This code i used today. I enter to telegram and open webapp and get id and save it for me and close all opened applications and enter again to telegram and open webapp but new id generated. And then I have two generated visitor id ))
something is wrong here. I think you need to do more testing with webview engines for Android. The main browser is chrome, but generating another id for the app browser and another id for chrome is a matter that needs to be looked at more strongly, I don't know.

**Comment by Finesse** [comment]
Answered at https://github.com/fingerprintjs/fingerprintjs/issues/1019#issuecomment-2243623384
