### ISSUE TITLE
Where's the open source library for blocking this library?

### ISSUE THREAD

**Issue by ShadowfaxRodeo** [fingerprintjs/fingerprintjs#631]
In issue #430 some of the contributors to fingerprintJS defend themselves by saying (i'm paraphrasing):

> We built this library open source so that people could better defend themselves from these privacy violations.

Well, if you care about people's privacy, then could you point us to the open source library you've built to defend people from the exploits you've found?

I'm not being facetious, does a defense against fingerprintJS library exist?

**Comment by Finesse** [comment]
Yes, you can find such extensions and browsers on GitHub. Here is an example: https://github.com/brave/brave-core. According to their blog, Brave uses FingerprintJS as a benchmark.

I’m closing this issue because it’s not a library issue. Please continue the discussion at #430 or the “Discussions section”.

**Comment by ShadowfaxRodeo** [comment]
Just to clarify, does FingerprintJS conribute to Brave? 

I'm guessing the answer is no. If that's the case, why not? If you care about people's privacy, why not use your knowledge to defend people instead of attacking them?

**Comment by Valve** [comment]
@ShadowfaxRodeo let's start from the correct premises first.

I'm the library creator.

**I never said this**: "We built this library open source so that people could better defend themselves from these privacy violations."

You're creating a misinformation by attributing this quote to me.

I started the library for other reasons, which I outlined here: https://github.com/fingerprintjs/fingerprintjs/issues/430#issuecomment-467263879

I never contributed to Brave and don't have plans to do so.

Happy to answer more questions.

**Comment by ShadowfaxRodeo** [comment]
I was paraphrasing — and I think I accurately captured the sentiment behind your reasons.

What your library does is violate people's privacy — specifically aimed at people who have taken steps to protect their privacy. That's why I ask if you also maintain a library for defending against these attacks. 

Knowing that you do not proves you don't care at all about how people use what you've created.

You're not an iron monger, this is not a raw material. This is the finished product, and it's a weapon.
