### ISSUE TITLE
Typescript compile issue

### ISSUE THREAD

**Issue by tootsweet** [fingerprintjs/fingerprintjs#651]
Hello,

Since version 3.3.0, I have the following error message while building my app:

![Screenshot 2021-04-23 at 10 48 39](https://user-images.githubusercontent.com/27771251/115855743-e6f07780-a42b-11eb-9135-66e85ead12ef.png)

I contacted the support team and they instructed me to open an issue here.

I am using react-scripts to build the app.
The "skipLibCheck" option in tsconfig.json is set to true

**Comment by Finesse** [comment]
Do you use FingerprintJS or FingerprintJS Pro? Could you please paste your package.json content here?

**Comment by Finesse** [comment]
@tootsweet FingerprintJS supports TypeScript v4.0 or newer. A couple of solutions for you:

- Update TypeScript to version 4 or newer
- Refuse using the TypeScript typing provided by our NPM package. In order to do it, replace `import ... from '@fingerprintjs/fingerprintjs-pro'` with `import ... from '@fingerprintjs/fingerprintjs-pro/dist/fp.esm.min'` in your `.ts` files and add the following line to a `.d.ts` file (if there is no such file, create one anywhere with any name): `declare module '@fingerprintjs/fingerprintjs-pro/dist/fp.esm.min';`

Please let me know if it helps.

**Comment by tootsweet** [comment]
I upgraded Typescript to v4. Thank you.
