### ISSUE TITLE
Server API cannot correctly detect windows version

### ISSUE THREAD

**Issue by Darkar25** [fingerprintjs/fingerprintjs#679]
### Scenario

- What's the scenario, what happens and what did you expect to happen? does not matter if user uses win10 or win8.1 server api will always return win10
- What device and browser are you using? Other, Windows 8.1, Opera browser
- What version of fingerprintjs are you using? Pro 3.3.1

### Fingerprint data

If applicable, provide the FULL DATA of both/all fingerprints using this page: https://fingerprintjs.github.io/fingerprintjs/.
Alternatively, provide a JSFiddle that reproduces the bug.

**Comment by makma** [comment]
Hello, @Darkar25!
Thank you for your issue. If I understand correctly, your issue is connected exclusively with our FingerprintJS PRO product. Since it is a separate product and this issue might require providing some sensitive or confidential information, please contact our support at [support@fingerprintjs.com](mailto:support@fingerprintjs.com
) directly. We will try to help you however we can.
Regards,
martin

**Comment by Darkar25** [comment]
> Hello, @Darkar25!
> Thank you for your issue. If I understand correctly, your issue is connected exclusively with our FingerprintJS PRO product. Since it is a separate product and this issue might require providing some sensitive or confidential information, please contact our support at [support@fingerprintjs.com](mailto:support@fingerprintjs.com) directly. We will try to help you however we can.
> Regards,
> martin

I don't think so...i think it doesn't matter what version of fpjs you are using, its the API that makes this mistake...

**Comment by Valve** [comment]
@Darkar25 oss version of fingerprintJS does not use our Pro API.
If you interact with an API, it's 100% a pro version. 
Thanks
