### ISSUE TITLE
Add this repo to 'fraud-detection' category of free APIs

### ISSUE THREAD

**Issue by Valve** [fingerprintjs/fingerprintjs#688]
https://github.com/public-apis/public-apis

**Comment by makma** [comment]
I'm not sure whether the repo is suitable for non web API repositories. I skimmed quickly and I found web APIs listed only. This hypothesis also supports [their guidelines](https://github.com/public-apis/public-apis/blob/master/CONTRIBUTING.md). Neverthheless, I've [submitted our PRO product](https://github.com/public-apis/public-apis/pull/1903) to the security section, since there is no fraud-detection one.

**Comment by Valve** [comment]
@makma great, thanks. Let's see if they accept.

**Comment by Valve** [comment]
closing this as we won't be adding the OSS to the public APIs.
