### ISSUE TITLE
Tree-shaking doesn't work properly

### ISSUE THREAD

**Issue by ankitchouhan1020** [fingerprintjs/fingerprintjs#699]
### Scenario

  I'm using only `load` function from fingerprintjs. So I imported it like this.
  ```js
  import { load } from '@fingerprintjs/fingerprintjs'
  ```
  This should include only the `load` function in the bundled chunks. But it is including the whole fp.esm.js file in the webpack bundle.

### Reason
sideEffects work on file/module level. Since there is only one file being exported, it will include the whole file in bundled chunks.

### Possible Solution
Rollup has `preserveModules` setting that keeps individual files instead of bundling.
Ref: https://github.com/webpack/webpack/issues/9337#issuecomment-507179765

**Comment by Finesse** [comment]
Hi @ankitchouhan1020. The `load` function requires all the rest code of the library, so if you import `load`, nothing will be removed during a tree-shaking. What do you expect to be left/removed in your code after tree-shaking the FingerprintJS library?

Webpack doesn't apply in-file tree-shaking in development mode and does apply in production mode. I've just checked it with Webpack 4.44.2. Not doing tree-shaking in development mode is an expected behavior from our point of view.

The only issue I see is the presence of some top level declarations that stay after tree-shaking a code that imports something other than `load` from FingerprintJS. I'll fix it.

**Comment by ankitchouhan1020** [comment]
Hi @Finesse, I missed this. Initially, when looked into `agent.ts`, there were many named exports so I thought somehow we can remove them from the bundle.

Thanks for the clarification. Closing this.
