### ISSUE TITLE
PC with Multiple Screens

### ISSUE THREAD

**Issue by prototype23** [fingerprintjs/fingerprintjs#706]
### Scenario

- What causes the fingerprint to change?
A pc with multiple screens. 
- What device and browser are you using?
Windows 10, Firefox 93 & Chrome 94.0.4606.81 (Official Build) (64-bit)
- What version of fingerprintjs are you using? 
V3.3.0

### Fingerprint data

Provide the FULL DATA of both/all fingerprints using this page: https://fingerprintjs.github.io/fingerprintjs/.
Alternatively, provide a JSFiddle that reproduces the bug.
[Right-monitor.txt](https://github.com/fingerprintjs/fingerprintjs/files/7347383/Right-monitor.txt)
[Left-monitor.txt](https://github.com/fingerprintjs/fingerprintjs/files/7347384/Left-monitor.txt)

**Comment by Finesse** [comment]
Hi @prototype23. Do you mean that you get different fingerprints when the browser window is on different screens? If yes, this is by design. Screen resolution is a good source of entropy. The instability caused by multiple monitors is acceptable for us, so we keep using screen resolution to calculate the fingerprints. Do you have ideas of how to solve it?

If this instability is not ok for you, you can exclude the screen resolution from the fingerprint. Exclude the `screenResolution` and `screenFrame` components using [this guide](https://github.com/fingerprintjs/fingerprintjs/blob/master/docs/extending.md#extending-fingerprintjs).

**Comment by prototype23** [comment]
Hi @Finesse, thanks for your reply. 

In my case, `screenFrame` changes the entropy, i have two monitors with the same resolution and depending from where i open the demo, visitor id changes. For my needs/understanding this should not happen. But since this is your design and you provide a guide how to exclude components that affect the entropy, i'm ok with that.

Please close this issue.

**Comment by Finesse** [comment]
Fingerprinting is a trade-off between sensitivity (the high number of unique fingerprints) and stability (the low chance of a device to get different fingerprints). We try to keep the optimal balance, but everybody has their own preferred balance, so we suggest [a way to change the balance](https://github.com/fingerprintjs/fingerprintjs/blob/master/docs/extending.md).
