### ISSUE TITLE
Duplicate Geometry Data When Using Firefox - Confirmed Across Multiple Devices

### ISSUE THREAD

**Issue by AdamaTNT** [fingerprintjs/fingerprintjs#728]
The geometry segment of the fingerprints are busted on Firefox. I've replicated it multiple times. Duplicates occur on laptops, desktops and mobile devices. Duplicates occur cross devices too (i.e. laptop geo = mobile geo, etc). Firefox version does not seem to matter.

Have not been able to locate on any other browser so far...

When combined with other data, we can still somewhat achieve "uniqueness" but I'd recommend an alternative implementation for FF.

### Scenario
- Visit this page: https://fingerprintjs.github.io/fingerprintjs/
- Visit on Firefox v.88 - on device A
- Visit on Firefox v.95.0.1 - on device B

### Fingerprint data
- Everything else is fine, but the geometry + text parts are identical.

**Comment by makma** [comment]
Hello @AdamaTNT,
If the browser interprets the canvas data the same way among various versions of the browser, the canvas entropy component remains unchanged. This is the desired behaviour.

For example, Firefox on Mac (or Windows) and iOS use different engines. When you try to generate a fingerprint on these platforms, you will get the different entropy components for canvas.

> I'd recommend an alternative implementation for FF.

What do you mean by an alternative implementation?

**Comment by makma** [comment]
Closing due to the lack of response.

**Comment by AdamaTNT** [comment]
Hey, just saw that this got closed. I think there is a misunderstanding as it's not just different versions of the browser that's the issue. The issue is different devices that use Firefox. Whether they use similar or different devices is incidental.

Am I missing something? I thought different devices would show different geometry fingerprints.

**Comment by makma** [comment]
Hi @AdamaTNT ,
When different browsers use the same logic that handles the rendering of canvas and the result is the same, we use the same entropy source in the FingerprintJS.

**Example 1**
Firefox v.88 - on device A (e.g., Win 10), Firefox v.95.0.1 - on device B (e.g., Win 10) - The canvas might be the same if the browser's logic processes canvas the same way.

**Example 2**
Firefox X on Win 10, Firefox X on iOS - canvas entropy source will be probably different since Firefox on Win 10 uses Gecko engine, whereas Firefox on iOS uses WebKit engine.

> Am I missing something? I thought different devices would show different geometry fingerprints.

No, it's possible the different devices might interpret the geometry data the same way therefore they will calculate the same entropy source.

**Comment by makma** [comment]
Closing due to the lack of response.
