### ISSUE TITLE
Generating visitorId across browsers

### ISSUE THREAD

**Issue by convodevteam** [fingerprintjs/fingerprintjs#822]
Hey,
Is it possible to generate the same visitorId across different browsers?
When I use the basic visitorId it changes every time...Is it possible to create this based on different aspects of data collected?

**Comment by makma** [comment]
Hello @convodevteam,
Both, opensource FingerprintJS (generating fingerprints) and Fingerprint Pro (generating visitorIds) are browser fingerprinting tools. That means they generate identifiers for browsers, not devices. Can you explain your scenario, please?

> When I use the basic visitorId it changes every time

Could you elaborate on this, I'm not sure I understand.

**Comment by hckhanh** [comment]
Hi @makma, I am building a promotion system. I want to prevent user use multiple browsers to abuse my campaign's resources. Is there any way to deal with it? For the logic, the user can only use one coupon per device. But if a user has 5 different browsers, the coupon can be used 5 different times. As I know IP is not a reliable way, since it can be easily changed.

**Comment by Valve** [comment]
@hckhanh It's correct, if a device has 5 browsers, this device will have 5 different fingerprints. However this list is still finite and it's not easy to get more than several browsers per device. 
We are not planning to do anything about it, because our tool is not designed to completely stop fraud, but to reduce it significantly. 
Even if we did have one fingerprint per device, an attacker could use multiple devices and still have multiple IDs, so since it's not possible to limit it to only one ID per person, we don't try to make it one ID per device.
Instead we focus on making this list finite (i.e. not growing indefinitely). Any other tools, such as those that rely on limiting by IPs/emails will always have to deal with potentially infinite lists and thus are less reliable.
