### ISSUE TITLE
FingerprintJS pro does not respect the defined subdomain

### ISSUE THREAD

**Issue by zoontek** [fingerprintjs/fingerprintjs#825]
Hi 👋

We are currently using FingerprintJS pro mainly for the BotD product and defined a custom subdomain in your dashboard.
But even if it seems to be correctly configured (`Issued` is checked + we correctly set the library config), the library ignore it and tries to load it from `https://eun1.fptls.com` (and is being blocked by AdBlockers)

```ts
FingerprintJS.load({
  region: "eu",
  apiKey: env.FINGERPRINT_PUBLIC_KEY,
  endpoint: env.FINGERPRINT_ENDPOINT,
});
```

Which is annoying, since we subscribe to the pro offer mainly for this exact feature.
Do you have an idea of what could go wrong here?

#### Environment infos
```json
"@fingerprintjs/fingerprintjs-pro": "3.7.1"
```

**Comment by Valve** [comment]
@zoontek thanks for letting us know about this issue.
Can you please disable the TLS using this param: https://dev.fingerprint.com/docs/js-agent#disabletls
Let us know if that fixes the issue.

**Comment by Finesse** [comment]
There are 2 endpoints in FingerprintJS Pro. You've changed only one of them. `https://eun1.fptls.com/` is the TLS endpoint. You can either disable the TLS request like @Valve has suggested, or change the URL with the [tlsEndpoint](https://dev.fingerprint.com/docs/js-agent#tlsendpoint) option.

**Comment by zoontek** [comment]
@Finesse Is the TLS endpoint value the same as endpoint? (when a custom subdomain is set)

**Comment by Valve** [comment]
The endpoint is separate from the TLS endpoint. You set a custom subdomain for endpoint, which is required to make the JS agent work, because this is where the data will be sent from users' browsers.
The TLS endpoint is an optional (but recommended) pre-requisite, that improves the identification accuracy.
Since you're using BotD only, the TLS endpoint is not really needed for you and you should just disable it.
