### ISSUE TITLE
Fingerprint Pro

### ISSUE THREAD

**Issue by xiaowang-web** [fingerprintjs/fingerprintjs#860]
How do Fingerprint Pro Premium versions generate the same Fingerprint across different browsers on the same device? How do I set Fingerprint Pro option to exclude browser parameters
![D32B228C-DECF-4FC2-B734-05C66E3C00D6的副本](https://user-images.githubusercontent.com/22915319/211515869-07da5d56-8610-4b88-a2d3-812754930c15.png)

**Comment by Finesse** [comment]
> How do Fingerprint Pro Premium versions generate the same Fingerprint across different browsers on the same device?

They don’t. Both FingerprintJS and FingerprintJS Pro are designed to identify browsers, not devices. Luckily, the number of browsers per device is limited.

> How do I set Fingerprint Pro option to exclude browser parameters

You can’t do it by yourself. Our engineers can tune the identification algorithm for you. Please reach the Pro support at support@fingerprint.com for this.

I’m closing this issue because it’s related to Fingerprint Pro, not FingerprintJS.
