### ISSUE TITLE
iOS: Pro Version Fingerprint changes after device reset

### ISSUE THREAD

**Issue by bugreporter321** [fingerprintjs/fingerprintjs#955]
### Scenario

The Fingerprint of the pro Version changes unexpectedly after reset of an ios device.
mobile Safari / ios17

Shouldn‘t the fingerprint remain same? Otherwise, is the pro version dependent on an evercookie in mobile safari? The fingerprint is stable after device reset.

**Comment by JuroUhlar** [comment]
Hi @bugreporter321!

This repository contains the source-available library FingerprintJS. It seems your question is related to Fingerprint Pro Identification on the iOS platform and would be more suitable to ask at https://github.com/fingerprintjs/fingerprintjs-pro-ios, consider posting it there. 

But as a quick answer, my understanding is that getting a new visitor ID after a factory reset is expected behavior. A factory reset implies a device being sold or handed over to a different person so assigning a new visitor ID makes sense for most use cases.

**Comment by bugreporter321** [comment]
What attributes of safari could change on each reset?
I was asking regarding pro version, I thought you maintain both if these as the pro version is advertised throughout the place.
Yet I wonder, if pro version is based on some dark magic, like usage of exploits, supercookies or similar, and not on actual fingerprinting in terms of fingerprintjs.

**Comment by JuroUhlar** [comment]
Yes, we maintain both the source-available FingerprintJS and the Pro version, but they work differently so I always try to clarify to avoid confusion.

The Pro version is based on FingerprintJS but collects more signals (including some server-side and proprietary signals) and differs in how the collected signals are processed. FingerprintJS just hashes them into a string and that’s the ID you get. Fingerprint Pro applies an advanced identification algorithm, leveraging machine learning and fuzzy matching to compute a more accurate visitor ID with a much longer lifetime.

See our documentation for a more detailed [breakdown of the differences](https://dev.fingerprint.com/docs/identification-vs-fingerprintjs).

**Comment by bugreporter321** [comment]
Hi JuroUhlar, I cannot imagine the fingerprint can work this way without some sort of state abuse on client side. In europe, the GDPR demands that personal data is to be deleted on request of the user. Could you please explain how to delete the state that the pro version has maintained inside my browser?

**Comment by Valve** [comment]
Hi @bugreporter321 
If you'd like to delete your personal data according to GDPR regulations, please email us at support@fingerprint.com and we'll process your GDPR data deletion request right away.

Thanks
