### ISSUE TITLE
Remove 'npm-monitoring' analytics.

### ISSUE THREAD

**Issue by blopker** [fingerprintjs/fingerprintjs#982]
### Scenario

- What's the scenario, what happens and what did you expect to happen?

I noticed that the npm version of fingerprintjs phones home to https://m1.openfpcdn.io/, with a %0.1 sampling.  The right behavior is that this library would not do that. It seems like this was configurable at one point (#950), but that was removed along with all references to this behavior.

It looks like developers can set `window.__fpjs_d_m = true` to disable this, but it feels invasive not to even mention it in the README. I've disabled it for now, but including this in such a sneaky way breaks trust in a big way.

Link to code: https://github.com/fingerprintjs/fingerprintjs/blob/c411aff111e5c79cdc37608d42632d4a66a8c1dc/src/agent.ts#L179

Please do the right thing and remove this, or at least tell people about it.

- What device and browser are you using?

Desktop Firefox

- What version of FingerprintJS are you using? (Bug reports not applicable to FingerprintJS master are subject to be closed without comment.)

Current version

**Comment by Valve** [comment]
Hello @blopker 
Thanks for creating this issue. 
You're right, we did remove mentions from the documentation how to disable the NPM monitoring.
This happened when we released a v4 of the library and changed its license to BSL.
You can read the details about this change here: https://fingerprint.com/blog/fingerprintjs-license-change

If you use v3 of the library, this version is still [documented](https://github.com/fingerprintjs/fingerprintjs/blob/v3/docs/api.md), and the library is available under a more permissive MIT license.

If you use the fourth version of the library (v4), public documentation no longer includes the description of how to remove the monitoring. 
This is done because the BSL license does not permit to use the library in production unless you purchased a commercial license. 
If you want to disable the monitoring w/out using the library in production, please email oss@fingerprint.com and we'll help you with this request. 

>Please do the right thing and remove this, or at least tell people about it.
This behavior is documented in the public API documentation here:
https://github.com/fingerprintjs/fingerprintjs/blob/master/docs/api.md
There are no plans to add to the documentation of the v4 how to disable the monitoring at this point.

Hope this is helpful.

I'm going to close this issue, please feel free to reopen with additional questions or concerns.

**Comment by blopker** [comment]
Thanks for the reply and confirming this will not be fixed.

I've gone ahead and removed this from our dependencies.

**Comment by punkpeye** [comment]
@blopker Did you find a good alternative?

**Comment by Valve** [comment]
Please note that forking the version 4 and later and using it in production would not be allowed by the license. Only v3 and before can be forked. Thanks

**Comment by Valve** [comment]
@ChetSocio for the NPM package, we have a monitoring in place, documented [here](https://github.com/fingerprintjs/fingerprintjs/blob/master/docs/api.md).
We don't send visitors to our servers when using this FingerprintJS library (to clarify our paid version sends the visitor ID values to our servers).

**Comment by blopker** [comment]
Another solution that doesn't violate the license:
```javascript
const originalOpen = XMLHttpRequest.prototype.open;
XMLHttpRequest.prototype.open = function(method, url) {
  if (url.includes('openfpcdn.io') {
    return; // Block the request
  }
  return originalOpen.apply(this, arguments);
};
```
Include that in a script tag in the HTML <head> somewhere.
